syms x y;
disp("1)");
f1 = x*exp(-x);
rez1 = limit(f1,x,inf);
disp(rez1);
disp("2)");
f2 = tan(x).^tan(2*x);
rez2 = limit(f2,x,pi/4);
disp(rez2);
disp("3)");
f3 = atan(1/(1-x));
rez3 = limit(f3,x,1,'right');
disp(rez3);